### ISSUE TITLE
Pre-trained model (Source model)?

### ISSUE THREAD

**Issue by jxthyatt** [Yushu-Li/OWTTT#1]
How can i obtain the pre-trained model (source model) from my own dataset?

**Comment by omega-cw** [comment]
> How can i obtain the pre-trained model (source model) from my own dataset?

Maybe you should train the model on your own dataset first?

**Comment by Yushu-Li** [comment]
Hi jxthyatt,

Thank you for reaching out! If you want to obtain a pre-trained model using your own dataset, you can just train and save a model using your own code.

To use the pre-trained model to perform open-world test-time training with this repository, you can load the saved weights into the same architecture. Create an instance of the model and load the weights using functions like load_state_dict.

Best regards,
Yushu Li
