### ISSUE TITLE
一点小问题

### ISSUE THREAD

**Issue by FlyGreyWolf** [Yushu-Li/OWTTT#2]
原文中的算法流程说到先进行测试，然后再进行adaption的操作。
为什么我看代码是先进行adaption然后再进行测试？

非常感谢作者的回复

**Comment by Yushu-Li** [comment]
非常感谢您提出的问题和对我们工作的关注。针对所提出的疑问，我非常愿意为您解答。

在论文中中提到的算法流程顺序是先进行测试，然后再进行参数调整的操作。在OWTTT中，我们的实现是基于[TTAC](https://github.com/Gorilla-Lab-SCUT/TTAC)仓库，其流程顺序相反。我们之所以选择先进行参数调整再进行测试的顺序实现，是为了确保与其他方法进行公平比较。

尽管算法中描述的流程与代码中的实现顺序略有不同，但我们也进行了相应的实验验证，发现先进行测试后再进行参数调整的实验结果与当前的实现在性能上没有什么显著的差异。差异仅为0.5个点左右，对于论文中的结论并不产生实质性的影响。

我感谢您对这个问题的指出，如果您的测试时训练场景对更好的及时性有要求，也可以考虑将OWTTT的测试阶段阶段提早到参数调整之前。根据我们的实验结果，这样的调整并不会对性能产生较大的影响。

希望这能够解答您的疑问，如果您有任何进一步的问题或需要更详细的解释，我很乐意提供更进一步的帮助。

再次感谢您的关注和支持！
